#amazonec2:
#    id:  "username"
#    key: "thisisthekey"

Rackspace:
  id:  "r_username"
  key: "r_key"

AmazonEC2:
  id: "aws_username"
  key: "aws_password"

LocalProvider:
  id: "local_id"
  key: "local_password"
